name: Update copyright year(s) in license file

on:
  schedule:
    - cron: '0 3 1 1 *'

permissions: {}

jobs:
  action-update-license-year:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@f180e962fa988db222d8f03ef4636750312d1b3d # v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
